# Generated by Django 2.1 on 2019-06-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ELevel',
            fields=[
                ('OBJECTID', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('PlaceNode', models.IntegerField()),
                ('PlaceName', models.CharField(max_length=50)),
                ('PersonName', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=20)),
                ('geometry', models.TextField(editable=False)),
            ],
            options={
                'verbose_name_plural': 'ELevel',
            },
        ),
    ]
