# Generated by Django 2.1 on 2019-06-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadHall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevel',
            name='Contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='elevel',
            name='PersonName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='elevel',
            name='PlaceName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
