# Generated by Django 2.1 on 2019-06-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadHall', '0002_auto_20190625_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevel',
            name='Email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
