# Generated by Django 2.1 on 2019-07-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadHall', '0006_blevel_clevel_dlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blevel',
            name='PlaceType',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clevel',
            name='PlaceType',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dlevel',
            name='PlaceType',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='elevel',
            name='PlaceType',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
