# Generated by Django 2.1 on 2019-07-22 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadHall', '0007_auto_20190704_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('functionality', models.CharField(max_length=50)),
                ('keyword', models.CharField(max_length=200)),
                ('returned', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Statistics',
            },
        ),
    ]
