# Generated by Django 2.2.7 on 2019-12-09 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeadHall', '0008_stat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stat',
        ),
    ]
